self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    # Not self hosted but actionlint still does not have a
    # release out supporting it
    - macos-13
    - macos-14
